// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM-q5bMR8rmEkmI7HmLuzV5e3anRlq-Gg',
    appId: '1:312794782466:web:0712e1eb1755cb0e11001b',
    messagingSenderId: '312794782466',
    projectId: 'alipro-29dec',
    authDomain: 'alipro-29dec.firebaseapp.com',
    storageBucket: 'alipro-29dec.appspot.com',
    measurementId: 'G-7YJ41RD625',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnYfIGPnT7TDQtcQA4LW2lkAEKp9_Rjtk',
    appId: '1:312794782466:android:3088cb11c2c5ea5b11001b',
    messagingSenderId: '312794782466',
    projectId: 'alipro-29dec',
    storageBucket: 'alipro-29dec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGtKRtqrG3--BYaG6oQr7uo0_4E_jUpMY',
    appId: '1:312794782466:ios:1d527f381fff6b8a11001b',
    messagingSenderId: '312794782466',
    projectId: 'alipro-29dec',
    storageBucket: 'alipro-29dec.appspot.com',
    iosClientId: '312794782466-kq4j7j27uc02sjp3ra5r77ahpcgf4ju6.apps.googleusercontent.com',
    iosBundleId: 'com.example.alipro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGtKRtqrG3--BYaG6oQr7uo0_4E_jUpMY',
    appId: '1:312794782466:ios:1d527f381fff6b8a11001b',
    messagingSenderId: '312794782466',
    projectId: 'alipro-29dec',
    storageBucket: 'alipro-29dec.appspot.com',
    iosClientId: '312794782466-kq4j7j27uc02sjp3ra5r77ahpcgf4ju6.apps.googleusercontent.com',
    iosBundleId: 'com.example.alipro',
  );
}
